### ISSUE TITLE
Autoplay next song

### ISSUE THREAD

**Issue by Slavison** [freddyouellette/fraudio#12]
Hi, first of all - thanks for your work!

Is it possible to autoplay next song when previous song is finished (if there are multiple <audio> tags on one page)?

I've googled some javascript code (below) which works with native html audio tag (without fraudio), but it doesn't work with fraudio enabled.

```
<script>
//Grab all audio elements
var audio = document.getElementsByTagName('audio');
//Create listeners
for (var i = 0; i < audio.length; i++) {
 audioListeners(i);
}
function audioListeners(i) {
 audio[i].addEventListener('ended', function() { 
  this.duration = 0; 
  this.pause();
  audio[i+1].play();
 }, false);
}
</script>
```

**Comment by freddyouellette** [comment]
Hi, thanks for opening this!

I think it's a great idea, so I added a setting for it. It's called `sequential_autoplay`. You can add it like this:
```
$.fn.fraudio.sequential_autoplay = true;
```

Then, all `.fraudio` elements will autoplay in order until the end of the page is reached.

Please download the latest version `v2.4.0` and let me know if this works for you, and then I can close this issue.

**Comment by Slavison** [comment]
Yeah, it works! Thanks, freddyouellette!
