### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by chromahoen** [freddyouellette/fraudio#4]
Hello, I found your script listed on https://www.jqueryscript.net/other/audio-player-fraudio.html

That website listed this repository. However, on the website linked above, it states specifically that it is offered under an MIT license. However, the code in this repository doesn't mention any license.

Would you help me understand how this being licensed?

**Comment by freddyouellette** [comment]
@chromahoen I've added a MIT LICENCE.md file. Feel free to use this package as you want.

**Comment by chromahoen** [comment]
Thank you!!
